// Compiled by ClojureScript 1.9.562 {:static-fns true, :optimize-constants true}
goog.provide('paren.component');
goog.require('cljs.core');
goog.require('cljs.core.constants');
paren.component.flipbox = (function paren$component$flipbox(p__14311,front,back){
var map__14314 = p__14311;
var map__14314__$1 = ((((!((map__14314 == null)))?((((map__14314.cljs$lang$protocol_mask$partition0$ & (64))) || ((cljs.core.PROTOCOL_SENTINEL === map__14314.cljs$core$ISeq$)))?true:false):false))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__14314):map__14314);
var props = map__14314__$1;
var flipped_QMARK_ = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__14314__$1,cljs.core.cst$kw$flipped_QMARK_);
return ((function (map__14314,map__14314__$1,props,flipped_QMARK_){
return (function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$section$flipbox,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$style,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$position,"relative",cljs.core.cst$kw$perspective,"800px"], null),cljs.core.dissoc.cljs$core$IFn$_invoke$arity$2(props,cljs.core.cst$kw$flipped_QMARK_)], 0))], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$div$card,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$style,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 7, [cljs.core.cst$kw$width,"100%",cljs.core.cst$kw$height,"100%",cljs.core.cst$kw$position,"absolute",cljs.core.cst$kw$transform_DASH_style,"preserve-3d",cljs.core.cst$kw$_DASH_webkit_DASH_transform_DASH_style,"preserve-3d",cljs.core.cst$kw$transition,"transform 1s",cljs.core.cst$kw$_DASH_webkit_DASH_transition,"transform 1s"], null),(cljs.core.truth_((cljs.core.deref.cljs$core$IFn$_invoke$arity$1 ? cljs.core.deref.cljs$core$IFn$_invoke$arity$1(flipped_QMARK_) : cljs.core.deref.call(null,flipped_QMARK_)))?new cljs.core.PersistentArrayMap(null, 2, [cljs.core.cst$kw$transform,"rotateY(180deg)",cljs.core.cst$kw$_DASH_webkit_DASH_transform,"rotateY(180deg)"], null):cljs.core.PersistentArrayMap.EMPTY)], 0))], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$figure$front,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 8, [cljs.core.cst$kw$margin,(0),cljs.core.cst$kw$position,"absolute",cljs.core.cst$kw$width,"100%",cljs.core.cst$kw$height,"100%",cljs.core.cst$kw$transform,"rotateX(0deg)",cljs.core.cst$kw$_DASH_webkit_DASH_transform,"rotateX(0deg)",cljs.core.cst$kw$backface_DASH_visibility,"hidden",cljs.core.cst$kw$_DASH_webkit_DASH_backface_DASH_visibility,"hidden"], null)], null),front], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$figure$back,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 8, [cljs.core.cst$kw$margin,(0),cljs.core.cst$kw$position,"absolute",cljs.core.cst$kw$width,"100%",cljs.core.cst$kw$height,"100%",cljs.core.cst$kw$transform,"rotateX(0deg) rotateY(180deg)",cljs.core.cst$kw$_DASH_webkit_DASH_transform,"rotateX(0deg) rotateY(180deg)",cljs.core.cst$kw$backface_DASH_visibility,"hidden",cljs.core.cst$kw$_DASH_webkit_DASH_backface_DASH_visibility,"hidden"], null)], null),back], null)], null)], null);
});
;})(map__14314,map__14314__$1,props,flipped_QMARK_))
});
